#include <16F917.h>
#device *=16
#device adc = 8
//Configuracion de los fusibles del microcontrolador
#FUSES NOWDT
#FUSES INTRC_IO
#FUSES NOPUT
#FUSES NOPROTECT
#FUSES MCLR
#FUSES NOCPD
#FUSES NOBROWNOUT
#FUSES IESO
#FUSES FCMEN
#FUSES NODEBUG

#use delay(clock = 8M)

#BYTE PORTD = 0x08
#BYTE PORTB = 0x06
#BYTE PORTA = 0x05
#BYTE TRISD = 0x88
#BYTE TRISB = 0x86
#BYTE TRISA = 0x85

#BYTE OPTION_REG = 0x181
#BYTE INTCON = 0x8B
#BYTE PIE1 = 0x8C
#BYTE PIR1 = 0x0C
#BYTE T1CON = 0x10
#BYTE TMR1L = 0x0E
#BYTE TMR1H = 0x0F
#BYTE TMR0 = 0x01

#BYTE OSCCON = 0x8F
